<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mail_login_email</name>
   <tag></tag>
   <elementGuidId>9655e5d8-3efa-4cf2-949a-d663f096c02f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;E-mail&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97a449ed-a4bb-4ada-8870-24cab5187ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa0e855b-fc30-4c6f-bbad-7a2ae6e95217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login_email</value>
      <webElementGuid>c35832c7-f06c-4701-a9c2-7c186c08c0ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_email</value>
      <webElementGuid>daa46ba8-2e60-441c-ae12-e76fc4044e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_email&quot;)</value>
      <webElementGuid>128dd0ff-45d6-40a1-b98c-c5098f8a3269</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login_email']</value>
      <webElementGuid>95ce0732-548d-4366-a712-f629cc236485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='singlePageForm']/main/form/fieldset/div/input</value>
      <webElementGuid>6c8b50f5-49f8-4bbb-a045-870f029731ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e6314a6c-0d6d-4259-bd82-786d123dc6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'login_email' and @id = 'login_email']</value>
      <webElementGuid>d0cdd1ed-f993-4635-b804-e48eb32851d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
